version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: terser
    versions:
    - 5.5.1
    - 5.6.0
    - 5.6.1
  - dependency-name: "@parcel/watcher"
    versions:
    - 2.0.0-alpha.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: imagemin
    versions:
    - 7.0.1
